---
title: "C Diff and Math!"
author:
- Jacob Carey
- Sarah Cox
- Katie Goodman
- Alex Pyden
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: |
  We looked at the Lanzas paper that investigated C Diff in a health care setting. Since then, there have been updates to care in C Diff, and we updated our model to account for this.

  There was math and disease. We did some differential equations and some simulations.

  Interest results that we found. It was really meaningful. Will change C Diff care forever.
output: pdf_document
---
\newpage

```{r chunks, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE,
                      message=FALSE)
```

```{r runme, eval=FALSE}
rmarkdown::render("doc/project.Rmd")
```

```{r libs}
# libraries
library(deSolve)
library(ggplot2)
library(dplyr)
library(tidyr)
theme_set(theme_classic())

# programs
source("../R/model.R")
```

```{r params}
# parameters
a.r <- 0.75
a.s <- 0.22
a.cn <- a.cp <- 0.01
a.d <- 0.01
alpha <- 0.5
theta <- 0.033
beta.c <- beta.d <- 0.007
f <- 0.6
epsilon <- 0.1
p <- 0.8
phi <- 0.2
k.r <- 0.33
k <- 0.15
k.d <- 0.068

# sequence of times
max.time <- 2.5e1
times <- seq(0, max.time, 1) 

# delta
delta <- 1e-1
```

```{r old-model}
# parameter vector
param <- c(a.r=a.r, a.s=a.s, a.cn=a.cn, a.cp=a.cp, a.d=a.d, alpha=alpha,
           theta=theta, beta.c=beta.c, beta.d=beta.d, f=f, 
           epsilon=epsilon, p=p, phi=phi, k.r=k.r, k=k, k.d=k.d)

# initial state
initial.state <- c(R=1e3, S=0, P=0, C=1e1, D=0)

model.old <- lsoda(initial.state, times, dx.dt.orig, param, delta=delta)
```

```{r new-model}
# parameter vector
param <- c(a.r=a.r, a.s=a.s, a.cn=a.cn, a.cp=a.cp, a.d=a.d, alpha=alpha,
           theta=theta, beta.c=beta.c, beta.d=beta.d, f=f, 
           epsilon=epsilon, p=p, phi=phi, k.r=k.r, k=k, k.d=k.d)

# initial state
initial.state <- c(R=1e3, S=0, C=1e1, D=0)

model.new <- lsoda(initial.state, times, dx.dt.new, param, delta=delta)
```

We reran the Lanzas model, but set delta equal to `r delta`.

```{r graphs-old}
data <- model.old %>% 
    data.frame() %>%
    tbl_df() %>%
    gather(compartment, size, R:D)

ggplot(data, aes(x=time, y=size)) +
    geom_line(aes(colour=compartment, linetype=compartment)) +
    ggtitle("Old Model")
```

We modified the Lanzas model and collapsed the colonized compartments into one colonized compartment, and did not distinguish between immune status. We chose to remove this distinction as it seemed somewhat arbitrary.

```{r graphs-new}
data <- model.new %>% 
    data.frame() %>%
    tbl_df() %>%
    gather(compartment, size, R:D)

ggplot(data, aes(x=time, y=size)) +
    geom_line(aes(colour=compartment, linetype=compartment)) +
    ggtitle("Collapsed Colonized Compartments")
```
